import type { EditPreset } from './types';

export const EDIT_PRESETS: EditPreset[] = [
  {
    id: 'cinematic',
    label: 'Make Cinematic',
    description: 'Film grain, slow pacing, cinematic dissolves',
    emoji: '🎬',
    pacing: 'slow',
    subtitleStyle: 'documentary',
    effects: ['film-grain', 'light-leak', 'vignette'],
    transitions: ['dissolve', 'fade'],
    durationMultiplier: 1.2,
    color: 'amber',
  },
  {
    id: 'documentary',
    label: 'Documentary',
    description: 'Clean cuts, factual pacing, minimal effects',
    emoji: '📽️',
    pacing: 'medium',
    subtitleStyle: 'documentary',
    effects: ['color-grade'],
    transitions: ['cut', 'fade'],
    durationMultiplier: 1.0,
    color: 'blue',
  },
  {
    id: 'anime-edit',
    label: 'Anime Edit',
    description: 'Speed lines, flashes, punchy anime timing',
    emoji: '⚡',
    pacing: 'fast',
    subtitleStyle: 'anime',
    effects: ['anime-flash', 'manga-lines', 'zoom-punch'],
    transitions: ['flash', 'zoom-in'],
    durationMultiplier: 0.75,
    color: 'pink',
  },
  {
    id: 'tiktok-viral',
    label: 'TikTok Viral',
    description: 'Fast cuts, bold captions, hook-first structure',
    emoji: '🔥',
    pacing: 'fast',
    subtitleStyle: 'tiktok',
    effects: ['zoom-punch', 'speed-ramp'],
    transitions: ['cut', 'zoom-in'],
    durationMultiplier: 0.65,
    color: 'red',
  },
  {
    id: 'hyper-edit',
    label: 'Hyper Edit',
    description: 'Rapid cuts, glitch transitions, maximum energy',
    emoji: '💥',
    pacing: 'fast',
    subtitleStyle: 'animated',
    effects: ['speed-ramp', 'zoom-punch', 'anime-flash'],
    transitions: ['glitch', 'whip-pan'],
    durationMultiplier: 0.5,
    color: 'purple',
  },
  {
    id: 'emotional',
    label: 'Emotional Edit',
    description: 'Slow build, glow, keyword highlights',
    emoji: '💜',
    pacing: 'slow',
    subtitleStyle: 'keyword-emphasis',
    effects: ['glow', 'vignette', 'light-leak'],
    transitions: ['dissolve', 'fade'],
    durationMultiplier: 1.3,
    color: 'violet',
  },
  {
    id: 'storytelling',
    label: 'Storytelling',
    description: 'Narrative structure, clean pacing, context overlays',
    emoji: '📖',
    pacing: 'medium',
    subtitleStyle: 'documentary',
    effects: ['film-grain', 'color-grade'],
    transitions: ['dissolve', 'fade'],
    durationMultiplier: 1.1,
    color: 'green',
  },
  {
    id: 'commentary',
    label: 'Commentary',
    description: 'Reaction layout, overlay suggestions, podcast feel',
    emoji: '🎙️',
    pacing: 'medium',
    subtitleStyle: 'default',
    effects: ['vignette'],
    transitions: ['cut', 'fade'],
    durationMultiplier: 1.0,
    color: 'cyan',
  },
  {
    id: 'podcast-clip',
    label: 'Podcast Clip',
    description: 'Audiogram-style, minimal motion, animated captions',
    emoji: '🎧',
    pacing: 'slow',
    subtitleStyle: 'animated',
    effects: ['color-grade'],
    transitions: ['fade'],
    durationMultiplier: 1.0,
    color: 'orange',
  },
  {
    id: 'motivational',
    label: 'Motivational',
    description: 'Punch-in quotes, bold typography, energy build',
    emoji: '💪',
    pacing: 'variable',
    subtitleStyle: 'keyword-emphasis',
    effects: ['zoom-punch', 'glow', 'light-leak'],
    transitions: ['zoom-in', 'flash'],
    durationMultiplier: 0.85,
    color: 'yellow',
  },
];
